### PR TITLE
Add support to get parse config with master key

### PR DESCRIPTION
**Pull request by mtrezza**
Adds support to retrieve the parse config with the master key. Allows to retrieve config parameters that require the master key to be retrieved.

Related to
- https://github.com/parse-community/parse-server/issues/5930
- https://github.com/parse-community/parse-server/pull/5954

### CODE REVIEW

**Comment by mtrezza** [comment]
Don't merge yet, integration test missing.

How can I add an integration test for getting config parameters that require the master key?
Currently the JS SDK does not support setting a parameter to require the master key. Can I write directly to the DB and flag a parameter to require the master key for a test?

**Comment by davimacedo** [comment]
You can:
- test if the rest command is sent correctly when passing the master key option; and
- add one test to the [integration tests](https://github.com/parse-community/Parse-SDK-JS/tree/master/integration/test) in which you could first use a REST API call to create the config and then use the SDK to retrieve the config.

**Comment by mtrezza** [comment]
@davimacedo, the test `Parse Config cannot get internal config parameter without masterkey` is failing, but locally it passes. Could it be that the tests are not running against parse server 3.8?

**Comment by dplewis** [comment]
@mtrezza This repo runs against the latest commit. Please do the following.

1. Delete package-lock.json
2. npm install
3. Commit new package-lock.json

**Comment by mtrezza** [comment]
@dplewis Thanks for cleaning this up so quickly!

**Pull request merged**
