### PR TITLE
style: Run Prettier for TypeScript declaration files

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

TypeScript declaration files `.d.ts` are generated with tabs instead of spaces and other formatting issues. This will cause `dtslint` to fail. Running Prettier + Lint --fix against these files leaves only type correctness checks and tests.

Screenshot 2024-05-17 at 5 39 43 PM

## Approach

Converts the following files to TS
```
FacebookUtils
ParseConfig
ParseOp
ParsePolygon
ParseSchema
```

* Add Facebook types for global FB variable
* Fixes the Check Types CI Job, this can now be a required job before merging PRs
* Add TS test suite example

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]

**Comment by mtrezza** [comment]
Quite impressive

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0)

**Pull request merged**
