### PR TITLE
fix: `LiveQueryClient.resubscribe` with Parse Server 7 causes many open connections

### LINKED ISSUE #2180: Change fields in LiveQueryClient.resubscribe to keys
### Issue Description
Change fields in LiveQueryClient.resubscribe to keys

https://github.com/parse-community/Parse-SDK-JS/blob/alpha/src/LiveQueryClient.ts#L303

### Steps to reproduce
* execute resubscribe
* parse-server logs
  - error | Connect message error Additional properties not allowed
  - info | Create new client: xxxx
  - many connection

### Actual Outcome
* no error

###  Environment

Server
* fields is removed
https://github.com/parse-community/parse-server/commit/38983e8e9b5cdbd006f311a2338103624137d013#2160

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

The `fields` attribute was changed to `keys` in Parse Server 7, `watch` was added in version 6. Resubscribing doesn't subscribe to the same query as the initial subscription. It was discovered that resubscribing with `fields` on version 7 will caused resubscribing every second which lead to many connections to the server ultimately resulting in a crash.

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/2180

## Approach

* Add keys and watch to resubscribe
* Fix the delay interval between resubscriptions

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Review by mtrezza — DISMISSED** [review]
Looks good; @akichim21 do you want to try this out before we merge, to see whether it solves the reported bug?

**Comment by mtrezza** [comment]
@dplewis changed PR title to describe the issue; is the new title ok?

**Comment by dplewis** [comment]
The title is perfect!

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.3](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0)

**Pull request merged**
