### PR TITLE
fix: subscription to a LiveQuery containing `ParseQuery.select` overrides properties

### LINKED ISSUE #1487: Keys are stripped upon subscription update with LiveQuery.select
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

When you have a LiveQuery using `.select`, the Parse JS SDK removes all other data from any existing matching object.

### Steps to reproduce

1. Create an object using .save, such as:

```js
const obj = new Parse.Object('Test')
obj.set('foo', 'bar');
await obj.save();
```

2. Use query.subscribe  on that object, using .select for certain keys

```js
const subscription = await new Parse.Query('Test').select('key').subscribe();
```
4. Trigger a subscription event from the cloud / a different client
5. Now `obj.get('foo')` will be undefined

### Actual Outcome

Incoming Live Query payload overrides all keys

### Expected Outcome

New incoming changes to merge with existing object

###  Environment

Server
- Parse Server version: `5.3`
- Operating system: `macOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `localhost`

Database
- System (MongoDB or Postgres): `mongo`
- Database version: `5`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `atlas`

Client
- Parse JS SDK version: `3.4.2`

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

When using `.select` with LQ, the Parse JS SDK strips out all keys on objects that have the same reference.

Related issue: #1487

### Approach

If `.select` is used in the LQ query, don't set all keys to undefined.

### TODOs before merging

- [x] Add tests

### CODE REVIEW

**Comment by mtrezza** [comment]
Waiting or https://github.com/parse-community/Parse-SDK-JS/issues/1487#issuecomment-1172873651 to resolve before merge

**Review by mtrezza — APPROVED** [review]
Looks good; waiting or https://github.com/parse-community/Parse-SDK-JS/issues/1487#issuecomment-1172873651 to resolve before merge

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.4.3-alpha.3](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.3-alpha.3)

**Comment by dblythy** [comment]
Thanks all!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.4.4-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.4-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.4.4-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.4-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.4.4](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.4)

**Pull request merged**
