### PR TITLE
fix: Remove support for Node <14

### LINKED ISSUE #1535: Remove Node 12 and 15 support
### New Feature / Enhancement Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation
Current build settings allow for node.js from version 8. But as far as I can see, it can only be used via parse-server which only supports nodejs from version 12.

### Feature / Enhancement Description
Could we change node support for Parse SDK JS as well? It would allow using ES7 features as object destructuring without the need for a polyfill.

### Example Use Case
As an example, [these lines](https://github.com/parse-community/Parse-SDK-JS/blob/e08f3b6f85ac16ff57da00b044b70159eaea95c1/src/ObjectStateMutations.js#L119-L121) seems to be the slowest (by far) in Parse.Object getter, which is called a lot in any code. Replacing these lines with a simple `const data = {...serverData};` is more than 80% faster according to jsbench.

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

Currently Parse JS SDK supports NodeJS versions that have reached EOL.

Related issue: #1535
Closes https://github.com/parse-community/Parse-SDK-JS/issues/1535

### Approach

Removes Node 12 support, changes build target to Node 14

### TODOs before merging

- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0)

**Pull request merged**
