### PR TITLE
refactor: Convert `CoreManager` to TypeScript

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Documentation missing from CoreManager.

## Approach

Converting CoreManager to TypeScript will lay the foundation for future conversions. CoreManager will be the key to removing circular dependencies which is main issue when converting the entire project to TypeScript.

### CODE REVIEW

**Comment by dplewis** [comment]
Type checking will be broken until ObjectStateMutations, ParsePush, ParseFile, ParseHook, ParseQuery, ParseUser are converted to TypeScript which will be done in the future.

**Comment by mtrezza** [comment]
So should we make the type check job optional in the CI and merge this?

**Comment by dplewis** [comment]
How do you make it optional?

**Comment by dplewis** [comment]
@mtrezza I made type checking optional for now. This is good to merge

**Comment by mtrezza** [comment]
I meant to remove the "required" option in the repo settings for that CI job. With your change the job will always pass in the CI, do we want that?

**Comment by dplewis** [comment]
@mtrezza I removed the CI change, do whatever you think is best.

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.9](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-alpha.9)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0)

**Pull request merged**
