### PR TITLE
Add Anonymous User Login

### PR DESCRIPTION
**Pull request by dplewis**
Similar to PHP SDK

### CODE REVIEW

**Comment by dplewis** [comment]
@flovilmart Should I add facebook and twitter to this?

**Comment by flovilmart** [comment]
What do you mean?

**Comment by dplewis** [comment]
Log in with facebook and twitter, like the php sdk

http://parseplatform.org/parse-php-sdk/classes/Parse.ParseUser.html#method_logInWithFacebook

**Comment by flovilmart** [comment]
They are already provided through the facebookUtils

**Comment by dplewis** [comment]
Ah I see, forgot that was there :P

**Comment by cjbland** [comment]
Would it be possible to add a way to convert an anonymous account into a "real" account? This is what I do on iOS (https://docs.parseplatform.org/ios/guide/#anonymous-users) but following the same procedure in JavaScript seems to retain the anonymous `authData`.

**Comment by dplewis** [comment]
@cjbland I don't see why not. iOS also has automaticUser, lazyLogin with LDS etc. 

If you want to get started on a new branch with `AnonymousUtils` and we can work on that.

**Comment by dplewis** [comment]
Closing as will add AnonymousUtils in the future

**Pull request closed without merging**
