### PR TITLE
fix: Docs fail with `Cannot find module 'taffydb'`

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

```
FATAL: Unable to load template: Cannot find module 'taffydb'
Require stack:
- /Users/dplewis/Documents/GitHub/Parse-SDK-JS/node_modules/@parse/minami/publish.js
- /Users/dplewis/Documents/GitHub/Parse-SDK-JS/node_modules/jsdoc/cli.js
- /Users/dplewis/Documents/GitHub/Parse-SDK-JS/node_modules/jsdoc/jsdoc.js
```

Ref: https://github.com/parse-community/Parse-SDK-JS/issues/2034

## Approach

* Update @parse/minami
* Update CI to check docs generates

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.1-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.1-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.1-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.1-alpha.1)

**Pull request merged**
