### PR TITLE
Move requestTask after sending request

### PR DESCRIPTION
**Pull request by JeromeDeLeon**
#1021 

@dplewis , I'm currently having problem with testing/experimenting in my project.

### CODE REVIEW

**Comment by dplewis** [comment]
This feature is for browsers only. Try to use a larger query perhaps the query is running to fast.

**Comment by JeromeDeLeon** [comment]
Nope, what I did was:

1. fork this project
2. npm install
3. move requestTask
4. go to my react project
5. npm install github:JeromeDeLeon/Parse-SDK-JS
6. Start the project

then I got an error saying that `/node_modules/parse/lib/browser/ObjectStateMutations.js`

**Comment by dplewis** [comment]
You should try to specify which branch you want

```
npm install github:JeromeDeLeon/Parse-SDK-JS#my-branch
```

**Comment by JeromeDeLeon** [comment]
Yes, I was able to download it but when I ran it, this happened `./node_modules/parse/index.js
Module not found: Can't resolve './lib/browser/Parse.js' in '/home/jdeleon/Projects/Own/test-app/node_modules/parse'`

I imported it with `import Parse from 'parse'`.

Did I skip something?

**Comment by dplewis** [comment]
@JeromeDeLeon If you want you can use [npm link](https://docs.npmjs.com/cli/link.html). I'll look into that issue you are having.

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/1030

**Pull request closed without merging**
