### PR TITLE
refactor: Fix TypeScript type correctness test

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

`npm run test:types`
```
Error: /home/runner/work/Parse-SDK-JS/Parse-SDK-JS/types/CoreManager.d.ts:1:15
ERROR: 1:15    expect  TypeScript@5.2 compile error: 
Module '"./ObjectStateMutations"' declares 'AttributeMap' locally, but it is not exported.
ERROR: 1:29    expect  TypeScript@5.2 compile error: 
Module '"./ObjectStateMutations"' declares 'ObjectCache' locally, but it is not exported.
ERROR: 1:42    expect  TypeScript@5.2 compile error: 
Module '"./ObjectStateMutations"' declares 'OpsMap' locally, but it is not exported.
ERROR: 1:50    expect  TypeScript@5.2 compile error: 
Module '"./ObjectStateMutations"' declares 'State' locally, but it is not exported.
ERROR: 3:15    expect  TypeScript@5.2 compile error: 
Module '"./ParseFile"' has no exported member 'FileSaveOptions'. Did you mean to use 'import FileSaveOptions from "./ParseFile"' instead?
ERROR: 3:32    expect  TypeScript@5.2 compile error: 
Module '"./ParseFile"' has no exported member 'FileSource'. Did you mean to use 'import FileSource from "./ParseFile"' instead?
ERROR: 7:15    expect  TypeScript@5.2 compile error: 
Module '"./ParseQuery"' has no exported member 'QueryJSON'. Did you mean to use 'import QueryJSON from "./ParseQuery"' instead?
ERROR: 9:15    expect  TypeScript@5.2 compile error: 
Module '"./ParseUser"' has no exported member 'AuthData'. Did you mean to use 'import AuthData from "./ParseUser"' instead?
ERROR: 10:15   expect  TypeScript@5.2 compile error: 
Module '"./Push"' declares 'PushData' locally, but it is not exported.
ERROR: 13:53   expect  TypeScript@5.2 compile error: 
Cannot find module './ParseHooks' or its corresponding type declarations.
ERROR: 279:[59](https://github.com/parse-community/Parse-SDK-JS/actions/runs/9116080664/job/25063872022#step:5:60)  expect  TypeScript@5.2 compile error: 
Cannot find name 'URL'.
ERROR: 280:50  expect  TypeScript@5.2 compile error: 
Cannot find name 'URL'.

/home/runner/work/Parse-SDK-JS/Parse-SDK-JS/types/ParseInstallation.d.ts:2:15
ERROR: 2:15    expect  TypeScript@5.2 compile error: 
Module '"./ObjectStateMutations"' declares 'AttributeMap' locally, but it is not exported.

/home/runner/work/Parse-SDK-JS/Parse-SDK-JS/types/ParseObject.d.ts:5:15
ERROR: 5:15    expect  TypeScript@5.2 compile error: 
Module '"./ObjectStateMutations"' declares 'AttributeMap' locally, but it is not exported.
ERROR: 5:29    expect  TypeScript@5.2 compile error: 
Module '"./ObjectStateMutations"' declares 'OpsMap' locally, but it is not exported.
```

## Approach

Convert the following to TypeScript
```
ObjectStateMutation
ParseFile
ParseHooks
ParseQuery
ParseRole
ParseUser
Push.js
TaskQueue
```

Added `dom` to `libs` in tsconfig for `Cannot find name 'URL'.` error
Fixed linting issues, for some reason the declaration files d.ts have parsing issues

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by dplewis** [comment]
@mtrezza This is ready for review, I'll fix the linting type issue in another PR.

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0)

**Pull request merged**
