### PR TITLE
fix: `Parse.Installation` not working when installation is deleted on server

### LINKED ISSUE #2124: Parse.Installation doesn't handle deleted Installation objects on server
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Deleted an installation in the database and it gets into a state where nothing works and it doesn't seem to be a way to get out of it.

The InstallationController never checks for server changes to object, so save() just fails since the local object has an id. And beyond cleaning the cache keys manually out of storage, there is no way to reset the installation locally.

### Steps to reproduce

1) Save the current installation
2) Delete it via Parse Dashboard
3) Try to get the current installation and save it.

### Approach
Parse Installation in the iOS SDK and this SDK should have similar functionaility.

[Installations cannot be deleted](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Parse/Internal/Installation/Controller/PFInstallationController.m#L88)

[We always want [currentInstallation fetch] to succeed.](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Parse/Internal/Installation/Controller/PFInstallationController.m#L59)

[We always want [currentInstallation save] to succeed.](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Parse/Source/PFInstallation.m#L249)

### Actual Outcome

The cache has a mismatch with the server and fails.

### Expected Outcome

Should properly save, fetch the installation always.

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

The InstallationController never checks for server changes to object, so save() just fails since the local object has an id. And beyond cleaning the cache keys manually out of storage, there is no way to reset the installation locally.

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/2124

## Approach

Ensure a new installation is created if installation is not found on the server when fetching / saving. This approach was taken from the iOS SDK

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by dplewis** [comment]
@mtrezza Conflicts have been resolve and this is ready for review.

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.1-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.1-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0)

**Pull request merged**
