### PR TITLE
refactor: Convert helper functions to TypeScript

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Approach

```
arrayContainsObject.js
canBeSerialized.js
decode.js
encode.js
equals.js
escape.js
isRevocableSession.js
parseDate.js
promiseUtils.js
unique.js
unsavedChildren.js
uuid
```

### CODE REVIEW

**Comment by dplewis** [comment]
@mtrezza Can you update the list [here](https://github.com/parse-community/Parse-SDK-JS/issues/2012#issue-1876509874) so we can keep track of progress?

**Comment by mtrezza** [comment]
Sure, just post there what's to update. Or is it only the list above?

**Review by mtrezza — APPROVED** [review]

**Comment by mtrezza** [comment]
Will merge after checking branch status after release publish.

**Comment by dplewis** [comment]
Just check off the list, some are missing and have already been converted to TS

CoreManager
InstallationController
Parse.js
ParseGeoPoint
ParseInstallation
ParseObject
ParseSession

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.1-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.1-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0)

**Pull request merged**
