### PR TITLE
refactor: Fix JSDoc warnings

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Updating the jsdocs eslint plugin caused warning to shows. This PR addresses them.

[see Issue](https://github.com/parse-community/Parse-SDK-JS/pull/1708/files#diff-d14b2dcbdb9c4dc7cad57a9f58577635dab37ed57062006716966fd22ab30d55)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.8](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0)

**Pull request merged**
