### PR TITLE
feat: Add support for custom EventEmitter

### LINKED ISSUE #1412: ReactNative - EventEmitter bug
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Unable to use Parse in React Native `0.65.1`

### Steps to reproduce

1. Create an empty React Native 0.65.1 iOS project 
2. Import Parse React Native: `import Parse from 'parse/react-native';`

### Actual Outcome

Error: 
```
/../node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:15
import type {EventSubscription} from './EventSubscription';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at
 Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/../node_modules/parse/lib/react-native/EventEmitter.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

###  Environment

- React Native iOS version: `0.65.1`

### Client
- Parse JS SDK version: `3.3.0`

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

A lot of JS frameworks that uses Parse throws errors when trying to use event emitter.

```
 Uncaught TypeError: Super expression must either be null or a function
    _inherits Babel
    Subscription LiveQuerySubscription.js:149
```
Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1412

## Approach

```
Parse.CoreManager.setEventEmitter(MY_EMITTER_CLASS);
Parse.initialize(...)
```
* Decouple EventEmitter from LiveQuery classes
* Decouple LiveQuery from LiveQueryClient
* Run test suite against react-native 
* Prevent overriding the custom event emitter

## Alternative
We could write our own EventEmitter in vanilla instead of `node:events` and polyfilling

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by dplewis** [comment]
@mtrezza This a new feature `feat:` but the side effects fixes a lot of issues. This forces a change in the import order. For instance, If you loaded LiveQuery before EventEmitter the SDK breaks. I would personally like to use `eventemitter3` for performance or create my own. This PR lays the groundwork for an isomorphic SDK

**Comment by mtrezza** [comment]
Do you mean this is a breaking change?

**Comment by dplewis** [comment]
Functionality is still the same but the new order allows the developer to control the flow. This shouldn’t be a breaking change. Moving `extend` an unloaded  class to the contructor makes this PR possible.

**Comment by mtrezza** [comment]
I want to make sure I understand this correctly, you wrote:

> This forces a change in the import order. For instance, If you loaded LiveQuery before EventEmitter the SDK breaks.

Do you mean that currently (pre-PR) if a developer loaded LiveQuery before EventEmitter the SDK crashes, but with this PR that is not the case anymore?

**Comment by dplewis** [comment]
We don’t support ES6. The many JS frameworks that uses Parse rearrange the imports. Unless they use the minimized version, we have no control meaning developers don’t have control.

**Comment by mtrezza** [comment]
Alright, if it's not a breaking change, we may just leave this open for a bit longer in case anyone from @parse-community/server has a comment on this. Otherwise we go ahead an merge.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.10](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.2.0-alpha.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0)

**Pull request merged**
