### PR TITLE
Add casting to integer on parse geopoint constructor. More flexibilit…

### PR DESCRIPTION
**Pull request by Krilwya**
Adding a support to construct geopoint from string and correct the issue I opened #592
Now it rightly create a geopoint with valid float numbers in order for the queries near, withinKilometers, etc.. works fine.

you can construct GeoPoint with string as followed : 
new GeoPoint("30", "30");
new GeoPoint(["30", "30"]);
new GeoPoint({latitude: "30", longitude: "30"});

all those equals the following number constructed geopoint ; 
new GeoPoint(30, 30);

It also add more flexibility if you retrieve your gps data from an existing db or a REST/API.

### CODE REVIEW

**Comment by dplewis** [comment]
@flovilmart I think we have a flaky test here. Can you take a look?

**Comment by dplewis** [comment]
@flovilmart Is this good?

**Comment by flovilmart** [comment]
I'm not sure about this one, this looks like a total mess of possible contructors, while it can be solved externally with helpers.

**Comment by flovilmart** [comment]
Closing at it clutters the codebase and it can be achieved with your own helper functions if really needed.

**Pull request closed without merging**
