### PR TITLE
fix: `LiveQuerySubscription.unsubscribe` resolves promise before unsubscribing completes

### LINKED ISSUE #1720: Ensure live query subscription unsubscribes
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Feature / Enhancement Description

The SDK ensures that live query subscribes successfully with a promise. The same should be applied to `unsubscribe`.  This could be used in the SDK test suite to ensure connections to the server are closed.

### Example Use Case

Using a promise would be a breaking change but would be aligned with `subscribe`
```
await subscription.unsubscribe();
```

Using a callback is an alternative
```
subscription.unsubscribe((error) => {});
```

Edit: I think we can support both

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1720

## Approach

* Ensure promise resolves
* Remove duplicate test

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by mtrezza** [comment]
Is this a breaking change? If yes, can it be made a non-breaking change?

**Comment by dplewis** [comment]
This isn't a breaking change

**Comment by mtrezza** [comment]
I'm asking because you [wrote](https://github.com/parse-community/Parse-SDK-JS/issues/1720#issue-1566993870):

> Using a promise would be a breaking change but would be aligned with subscribe

Just to confirm, it's not a breaking change?

**Comment by dplewis** [comment]
I realized that `unsubscribe` already returned a promise. It just ran in the background and still does after this PR.

**Comment by mtrezza** [comment]
Got it, thanks for confirming, just wanted to make sure

**Comment by mtrezza** [comment]
So is this actually a bugfix then because the promise resolved before the unsub has completed? Like:

> fix: `LiveQuerySubscription.unsubscribe` resolves promise before unsubscribing completes

**Comment by dplewis** [comment]
Thats correct

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.8](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0)

**Pull request merged**
