### PR TITLE
⚡️ Release 2.16.0

### PR DESCRIPTION
**Pull request by dplewis**
Sorry for the wait!

### CODE REVIEW

**Review by davimacedo — APPROVED** [review]
LGTM!

**Comment by dplewis** [comment]
@davimacedo I'm going to focus on the Parse-Dashboard. I see test failing because of crypto-js.

**Comment by davimacedo** [comment]
It makes sense. Let me know if you need any help. There are some open PRs over there as well. We can work together and sort things out.

**Review by TomWFox — COMMENTED** [review]
Nice, idempotency is a fantastic addition.

**Pull request merged**
