### PR TITLE
fix: Local datastore query with `containedIn` not working when field is an array

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

Similar to https://github.com/parse-community/parse-server/pull/8128

Closes: Added additional test case for https://github.com/parse-community/parse-server/issues/8335

### TODOs before merging

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by mtrezza** [comment]
Thanks for the PR; could you rephrase the PR title to make it easier to understand in the changelog what this actually fixes?

The 2 references are related to LiveQuery - is this also LiveQuery related?

**Comment by dplewis** [comment]
@mtrezza The LocalDatastore is internally code copied from LiveQuery meaning queries that LiveQuery supports the LocalDatastore should support too. Those are just additional test cases that doesn't exist server side.

**Comment by mtrezza** [comment]
How would you best describe the fix in `src/OfflineQuery.js`?

> Local datastore not working properly for `Parse.Query.containedIn` where field is an array

Or something more specific?

**Comment by dplewis** [comment]
> How would you best describe the fix in `src/OfflineQuery.js`?

It's the same fix as the `QueryTools.js` in the latest 5.4.0 release of the server

https://github.com/parse-community/parse-server/pull/8128/files#diff-13c52f9da4d37c7dc0bd3e9e845716de38a13e2a8632465ea167422762d5a9b6

**Comment by dplewis** [comment]
> Or something more specific?

For non array fields you are comparing a single value against an array. This fix checks a array against an array recursively. As I write this I realized that `nonContainedIn` is broken and will return always return an object.

Without this fix we would have to rely on.

`haystack.indexOf(needle) > -1`

Array.indexOf(Array) will always return -1

**Comment by mtrezza** [comment]
The other PR is called "fix: liveQuery with containedIn not working when object field is an array". So how about this:

> fix: Local datastore query with `containedIn` not working when field is an array

What do you conclude from the `nonContainedIn`? I haven't looked into the logic so far...

**Comment by dplewis** [comment]
@mtrezza I write a few additional test cases, I also think there might be an issue with `containedBy` queries.

**Comment by dplewis** [comment]
@mtrezza This is ready for review

**Comment by mtrezza** [comment]
Re-running CI

I'm curious about these fails: https://github.com/parse-community/Parse-SDK-JS/actions/runs/4019619971/jobs/6906679057; it seems a connection error, do you have any idea what that could be since you've been looking at the flaky tests?

**Comment by dplewis** [comment]
> it seems a connection error, do you have any idea what that could be since you've been looking at the flaky tests?

@mtrezza I suspect it might be an issue with `reconfigureServer`. `allowCustomObjectId` tests seem most common but I have seen `eventuallyQueue` tests also fail with his error. You can see where the first occurrence of the error is thrown.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.6](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.1-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.1-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.1)

**Pull request merged**
