### PR TITLE
Support for Aggregate Queries

### PR DESCRIPTION
**Pull request by dplewis**
Support for `distinct()` and `aggregate()` queries.

Pending: https://github.com/parse-community/parse-server/pull/4207

### CODE REVIEW

**Comment by oallouch** [comment]
That's really great. All the power of MongoDB in Parse !
Do you have prepared a little documentation update for this ?

**Comment by dplewis** [comment]
@oallouch Documentation will be coming soon!

**Comment by dplewis** [comment]
@flovilmart Can you check this?

**Comment by flovilmart** [comment]
code looks good, but would it be too much to ask for added Jest tests for this class?

**Comment by flovilmart** [comment]
Thanks @dplewis for this! 🙏

**Comment by dplewis** [comment]
@flovilmart Quick question. I was lazy and didn't require aggregate in the query controller https://github.com/dplewis/Parse-SDK-JS/blob/aggregate/src/CoreManager.js#L272

Is that ok? I can update all the tests if needed.

**Comment by flovilmart** [comment]
That would be better to add those methods now so we don’t have to come back to it later.

**Comment by flovilmart** [comment]
CoreManager-test is failing (it specifically validates the interface)

**Comment by flovilmart** [comment]
Perfect! Waiting for CI but it all looks great!

**Comment by dplewis** [comment]
@flovilmart How does this look?

**Comment by flovilmart** [comment]
Perfect 👌🏻

**Pull request merged**
