### PR TITLE
feat: Support dot notation on array fields

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Using Dot notation on array fields messes up the internal state of objects. Most notably internally they are handled like objects instead of arrays. This would prevent other array operations like `add`, `remove` from working. Also this may cause errors on the Server.

```
{ items: { '0': { count: 20 }, '1': { count: 5 } } }
```
instead of 
```
{ items: [{ count: 20 }, { count: 5 }] }
```

Closes: https://github.com/parse-community/Parse-SDK-JS/pull/1343

## Approach

Update ObjectStateMutation `estimateAttributes` and `commitServerChanges`.
`estimateAttributes` is called whenever `obj.attributes` is accessed.
`commitServerChanges` is called on `obj.save` and `obj.fetch`

## TODO
- [ ] Run against Parse Server test suite

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by mortenmo** [comment]
so the syntax is `set('arr.1.name', 'Bob');`?  I'd be curious if the server creates the right mongo update to support this, might be worth a integration test.

Unrelated, I noticed in one of my PRs that `ObjectStateMutations.js` has a function `estimateAttribute` that doesn't seem to support dot-notation at all, while the plural `estimateAttributes` does (which you updated here). I couldn't find any usage of the first one, is it just dead code?

**Comment by dplewis** [comment]
> so the syntax is set('arr.1.name', 'Bob');? I'd be curious if the server creates the right mongo update to support this, might be worth a integration test.

I'm curious as well but https://github.com/parse-community/parse-server/pull/9115 will need to be merged first. I think it should work based on the tests I wrote.

> estimateAttribute that doesn't seem to support dot-notation at all

I think this might be dead code, good catch

**Review by mtrezza — APPROVED** [review]
Is this PR ready for merge?

**Comment by dplewis** [comment]
@mtrezza This is ready to merge.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.2.0)

**Pull request merged**
