### PR TITLE
ci: Add support for Parse Server 6

### LINKED ISSUE #1637: Prepare for Parse Server 6
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

The SDK needs to be prepared for the breaking changes coming with Parse Server 6.
As we can see in https://github.com/parse-community/Parse-SDK-JS/pull/1636, the tests are failing.

A PR to fix this may break compatibility with Parse Server <6; a compatibility table needs to be added to the README for Parse Server.

### Feature / Enhancement Description
n/a

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

SDK does not currently support Parse Server 6, as the startup method has changed.

Closes: #1637

### TODOs before merging

- [x] Add tests

### CODE REVIEW

**Comment by dblythy** [comment]
@mtrezza The SDK should still be compatible with previous versions, it's only the startup method which is a `devDependancy` that breaks the CI

**Comment by dplewis** [comment]
@mtrezza Is this ready to merge? I have to copy the startup code to make PR's

**Review by mtrezza — APPROVED** [review]
Looks good!
@dblythy is this ready for merge?

Is this a breaking change? If so, we'd need to compose a note for the changelog.

If this breaks compatibility with Parse Server <6, a compatibility table needs to be added to the README for Parse Server.

**Comment by dplewis** [comment]
@mtrezza Looks like its linted code and the server is only here for testing. No breaking changes.

**Comment by mtrezza** [comment]
There is also a change in package lock, that's strange if there are only test and lint changes.

**Comment by dplewis** [comment]
@mtrezza You can't test against latest of Parse Server without bumping it. In the package-lock.json they are all dev dependencies. `dev: true`. Dev deps don't affect the build

**Comment by mtrezza** [comment]
Ah right, we import the alpha branch of Parse Server here, hence the lock file changes. Really not an ideal solution.

Let's think this through once more. So this is actually not a `feat` commit, but a `ci` commit, since it's only adapting the tests. If we are adapting the tests for Parse Server 6, we are not testing anymore against Parse Server 5. Since Parse Server 6 has breaking changes, I assume there is a also a chance that the Parse JS SDK becomes incompatible with Parse Server 5 at some point.

It may be problematic that we are only testing with the latest Parse Server alpha branch. If we could add a CI test for at least the latest Parse Server 5 (branch `release-5.x.x`), we would know when the compatibility breaks.

**Comment by mtrezza** [comment]
So I guess this is also not a `feat` commit, but actually just a `ci` commit, since it's only test related, right?

**Comment by mtrezza** [comment]
Since we are preparing the Parse JS SDK 4 major release, I guess we could add a compatbility table to the README and say that JS SDK 4 is only compatible with Parse Server 6. That may not be true (yet), but it aligns with our premise that we only officially support versions that the CI tests against.

**Comment by mtrezza** [comment]
To get ahead here, let's merge this for now and assume the SDK stays compatible with Parse Server 5. We should add Parse Server 5 testing to the CI to verify compatibility, therefore opened https://github.com/parse-community/Parse-SDK-JS/issues/1651.

**Comment by mtrezza** [comment]
Node 18 fails repeatedly with the same error:

> 1) Parse User cannot save non-authed user
>  - Unhandled promise rejection: AssertionError [ERR_ASSERTION]: 101 == 206

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.6](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.6)

**Pull request merged**
