### PR TITLE
feat: Improve installation object `Parse.Installation.currentInstallation` to support web push notifications

### LINKED ISSUE #2112: Installation support for JS SDK
### New Feature / Enhancement Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

Other Parse SDKs (Swift/Kotlin, etc) supports the `Installation` object to handle push notifications etc. There seems in the JS SDK there is just a minimal implementation.

* For React Native/Expo, this is limiting, ideally it should work similar to build a RN app vs Swift/Kotlin.
* Web browsers also support notifications now, so supporting this in the SDK even for just web might be useful to some users.

### Feature / Enhancement Description

Similar to the phone SDKs, handle maintaining the Installation object per installation. Things like device type, tokens etc could be handled in similar ways probably relying on react native libraries for react native at least.

This isn't really asking for new functionality beyond what is available in other SDKs.

### Alternatives / Workarounds

You could probably handle this all manually today.

### 3rd Party References

In the other SDKs built for Mobile.

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Other Parse SDKs (Swift/Kotlin, etc) supports the Installation object to handle push notifications etc. There seems in the JS SDK there is just a minimal implementation.

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/2112

## Approach

* Improve existing Parse.Installation objects
* Add retrieving the current installation
* Improve documentation
* Add ability to override the installationController with custom controller
* Convert installation to TS

```
const installation = await Parse.Installation.currentInstallation();
installation.set('deviceToken', '123');
installation.set('deviceType', 'web');
installation.set('user', Parse.User.current());
await installation.save();
```
## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.9](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-alpha.9)

**Comment by mortenmo** [comment]
@dplewis This might be a general problem and not related to this PR/Web, but I accidentally deleted an installation in the database and it gets into a state where nothing works and it doesn't seem to be a way to get out of it.

The InstallationController never checks for server changes to object, so `save()` just fails since the local object has an id. And beyond cleaning the cache keys manually out of storage, there is no way to reset the installation locally.

Rest seems to work great though! and this is an edge case for sure. I just cleaned up the wrong things.

**Comment by dplewis** [comment]
@mortenmo That seems to be a problem. I was looking at the iOS SDK and this SDK should match it closely.

[Installations cannot be deleted](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Parse/Internal/Installation/Controller/PFInstallationController.m#L88)

[We always want [currentInstallation save] to succeed.](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Parse/Internal/Installation/Controller/PFInstallationController.m#L59)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0)

**Pull request merged**
