### PR TITLE
Greenkeeper/initial

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by dplewis** [comment]
@flovilmart long overdue 🙏

**Comment by flovilmart** [comment]
@dplewis not sure how to check if it's properly registered with greenkeeper :/

**Comment by dplewis** [comment]
Are the gulp packages needed?  As far as maintaining greenkeeper which packages are required

**Comment by flovilmart** [comment]
All the pacakges are needed, the JS SDK builds are generated with gulp. This could be updated in the future I believe.
 
For greenkeeper, I'm not sure if it's running correctly as it was not setup properly before.

**Comment by dplewis** [comment]
That’s true forgot about the build. I think greenkeeper is working because the bot is making commits on this PR

**Comment by flovilmart** [comment]
Nah, those are the old initial commits: I'm reinit it, PR moved to #588

The initial commits are just the ones from the initial setup, which did not go through the 1st time :/ as per #445

**Comment by dplewis** [comment]
Didn’t check the date on this lol

**Pull request closed without merging**
