### PR TITLE
fix: fix locfile

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

Regenerates lockfile

Related issue: #1515

### Approach

re-run `npm i`

### TODOs before merging

n/a

### CODE REVIEW

**Comment by dblythy** [comment]
Note: this PR is just proof that https://github.com/parse-community/parse-server/pull/8159 fixes the lockfile issue

**Comment by mtrezza** [comment]
I've converted this to DRAFT to make sure it doesn't get merged by mistake.

**Comment by dblythy** [comment]
Tests passing @mtrezza

**Comment by mtrezza** [comment]
Closed at this was just for CI testing purpose to fix #1515

**Pull request closed without merging**
