### PR TITLE
refactor: bump UUID dep, remove 'deep require' of uuid

### PR DESCRIPTION
**Pull request by jpgupta**
See UUID documentation - https://github.com/uuidjs/uuid#deep-requires-now-deprecated

### New Pull Request Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description
The way Parse requires the uuid package is discouraged by the maintainers, and seems to be causing issues with other dependencies in my project. 

Related issue:
https://github.com/parse-community/Parse-SDK-JS/issues/1491

### Approach
This PR updates the uuid dependency fro 3x to 8x, and modifies the way it is imported/required, to use a named import, instead of the deprecated deep require appraoch. 

I am not an expert in the nuances of JS import/require approaches so would appreciate some input from someone on this change -it seems to be sensible to me and in line with what the uuid project maintainers recommend (https://github.com/uuidjs/uuid#deep-requires-now-deprecated). 

### TODOs before merging

- [ ] Add entry to changelog

### CODE REVIEW

**Comment by mtrezza** [comment]
Could you take a look at the failing tests?

**Comment by jpgupta** [comment]
@mtrezza Yes I'll take a look this week 
(For reference / in case anyone can help - it seems to be a permissions related thing? Not sure if people come across this commonly when commiting to this repo for the first time?)

Screenshot 2022-06-12 at 12 44 25

**Comment by mtrezza** [comment]
Maybe rebasing this PR on alpha fixes this, see https://github.com/parse-community/Parse-SDK-JS/pull/1495.

**Comment by jpgupta** [comment]
@mtrezza I'll give that a go thank you!

**Comment by mtrezza** [comment]
It seems the package-lock file still has a conflict

**Comment by jpgupta** [comment]
@mtrezza - taking a look

**Comment by jpgupta** [comment]
@mtrezza - I'm seeing this message, could you kindly re-run this workflow?
Screenshot 2022-07-26 at 23 57 20

**Comment by mtrezza** [comment]
Did you recreate the package-lock file? 26,671 additions, 165 deletions looks unusual for this simple dependency upgrade.

**Comment by mtrezza** [comment]
@jpgupta Could you use the package-lock file from the alpha branch and do the dependency upgrade again?

**Comment by jpgupta** [comment]
@mtrezza sorry for the delay, bunch of things going on - will take a look at this in the next few days

**Comment by dplewis** [comment]
Closing for bot to recreate PR.

**Pull request closed without merging**
