### PR TITLE
fix: SDK builds incorrectly since release 3.5.0 causing various bugs

### LINKED ISSUE #1592: Parse.Query.first() not working after parse@3.5.0-alpha.4
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the version *4.5.0* of [Parse Server](https://github.com/parse-community/parse-server/releases) and the latest version of [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
Parse.Query.first() is not working after parse@3.5.0-alpha.4

### Steps to reproduce
let Product = Parse.Object.extend('Product'); 
const query = new Parse.Query(Product);
let result = await query.first();

***NB: *Product* is a name of a class.***

### Actual Outcome
throws error
error.code: undefined
error.message: Cannot read properties of undefined (reading 'className')

### Expected Outcome
object of 'Product' class

###  Environment
Using Parse JS SDK: 

Server
- Parse Server version: `4.5.0`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Back4app`

Client
- Parse JS SDK version: `3.5.0` 
- https://npmcdn.com/parse@3.5.0/dist/parse.min.js

### LINKED ISSUE #1593: Parse.User.save() does not work in parse@3.5.0
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the version *4.5.0* of [Parse Server](https://github.com/parse-community/parse-server/releases) and the latest version of [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
Parse.User.save() does not work in parse@3.5.0

### Steps to reproduce
let user = new Parse.User();
user.set("username", "xx");
user.set("email", "xx@xx.xx");
user.set("password", "xx");
saveduser = await user.save();

### Actual Outcome
It is saved/updated in the local session but not in the backend/server.

### Expected Outcome
Update the data in the backend/server.

###  Environment

Server
- Parse Server version: `4.5.0`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Back4app`

Client
- Parse JS SDK version: `3.5.0`

### LINKED ISSUE #1596: Parse.Query.subscribe() and Parse.Query.first() don't work in Parse v3.5.0
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Parse.Query.subscribe() and Parse.Query.first() throw errors upon calling
Query.first() is also recorded [here](https://github.com/parse-community/Parse-SDK-JS/issues/1592#issue-1432790510)
### Steps to reproduce

[Here is a Github Repository](https://github.com/aarondill/parseError) that includes files for use in testing this bug.
Create a Parse.Query and call subscribe() on it
alternatively create a LiveQueryClient and call subscribe() on it with a Parse.Query
### Actual Outcome

throws error "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'socket')" upon calling.
### Expected Outcome

Expected a subscription object
###  Environment

Client
- Parse JS SDK version: [Parse JavaScript SDK v3.5.0](https://unpkg.com/parse@3.5.0/dist/parse.min.js)

### LINKED ISSUE #1599: Removal of _this# variables in JS SDK v3.5.0
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases).

### Issue Description

**Removal of \_this# variables in JS SDK v3.5.0**

Within the Parse JS SDK, variables intended to capture the context of _this_ in certain contexts are generally called \_this, optionally followed by a number(i.e. \_this1), for the purpose of this report, I will call them \_this variables, ignoring the number, to increase readability and shorten length.

Using simple find tools(i.e. searching for var \_this), I found that **17 \_this** variables were removed from the Javascript SDK between v3.4.4 and v3.5.0. At first glance, this change seems positive, as it reduces memory required by the Parse SDK module, however, as can be seen in [issue #1596](https://github.com/parse-community/Parse-SDK-JS/issues/1596) and my discovery of [the issue causing it](https://github.com/parse-community/Parse-SDK-JS/issues/1596#issuecomment-1305038379) the removal of some of these \_this variables create issues that can halt functions and throw errors.

It seems possible that the contributor(s) related to the removal of these \_this variables was mistaken in the implementation of the _this_ keyword in (at least) functions passed to Promise.then() and therefore errors are thrown by the environment attempting to read properties of _this_, at times where _this_ evaluates to undefined in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#no_this_substitution).

It is greatly recommended that each removal of these \_this variables is reevaluated and that any necessary variables are reinstantiated into the SDK to avoid futher errors and issues.

Due to insufficient time and understanding of the code base of the Parse SDK, I am incapable of checking each and every removal, however the recent errors caused by these removals should certainly be considered and every precaution should be taken to prevent further issues from arising.

### Steps to reproduce

Due to the large scale of this issue, and the potential for some removals to be valid, I will not produce STP, however STP for the errors in the Query.first and Query.subscribe functions can be seen in [issue #1596](https://github.com/parse-community/Parse-SDK-JS/issues/1596).

### Actual Outcome

For certain functions, typeErrors are thrown and the program is halted.
(Potentially) For others, evaulation is continued and in incorrect value is returned or saved.

### Expected Outcome

Correct return values and database writes, without any errors thrown.

### Environment

Database

- Local or remote host: back4app (once more irrelevant)

Client

- Parse JS SDK version: v3.5.0

### Note

Due to the format of this issue, it does not quite fit the issue format, however, for lack of better location, I am placing this under generic issues. Please let me know if there is a better location for this issue.

### LINKED ISSUE #1601: Object.save() and Query.first() issues
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

I have a problem with saving and getting first object using `Parse.Query` in JS. The most strange thing is that in other my projects this code works seamlessly. I think that they are connected to each other, so I report about both of them in one time

- `await Parse.Query.first()` is resulting in exception, while `(await Parse.Query.find())[0]` works correctly
- `Parse.Object.save()` is resulting in undefined, not in issue

### Steps to reproduce

Code to reproduce the `new Parse.Query.first()` problem:
```JavaScript
const record = Parse.Object.extend('SyncVisitRecord'); //my class name string
const query = new Parse.Query(record);
query.equalTo("key", key);
const record1: Parse.Object = await query.first();
```
Code to reproduce the `new Parse.Object.save()` problem:
```JavaScript
const record = Parse.Object.extend('SyncVisitRecord'); //my class name string
const query = new Parse.Query(record);
query.equalTo("key", key);
const record1: Parse.Object = await (await query.find())[0];
record1.set('lang', "us");
        record1.save()
            .then((gameScore) => {
                console.log(gameScore)
            }, (error) => {
                console.log(error)
            })
```
### Actual Outcome

- `new Parse.Query.first()` problem outcome is `TypeError: Cannot read properties of undefined (reading 'className') at eval (parse.js:18430:39)`
- `Parse.Object.save()` problem outcome is `undefined`

### Expected Outcome

- I wait for regular Parse.Object
- I wait for the saved object in db and regular Parse.Object in console

### Environment

Server
- Parse Server version: `^5.2.1`
- Operating system: `Ubuntu 22.04.1 LTS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Oracle Cloud`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `^5.0.9`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- Parse JS SDK version: `^3.5.0`

### LINKED ISSUE #1614: Find/first issue with 3.5
### New Issue Checklist

- [ X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ X] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [ X] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
Unable to user Query.first on 3.5

### Steps to reproduce
Do a first() query with 3.5 client (the query work well with older versions, at least 3.4.2)

### Actual Outcome
giving a collection  'Mission' the query above return an error 

```
const t = await (new Parse.Query('Mission')) .select(['position', 'client']).equalTo('objectId', 'Etk9VWubwP')
           .first()
        console.log(t);
```

outputed error
Capture d’écran 2022-11-18 à 16 57 50

### Expected Outcome

On lower version
the same query work.
Capture d’écran 2022-11-18 à 16 58 50

###  Environment
Issue found on 3.5, work on 3.4.2.

Server
- Parse Server version: `5.3.3`
- Operating system: `Alpine16`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS`

Database
- System (MongoDB or Postgres): `mongo`
- Database version: `4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `ATLAS`

Client
- Parse JS SDK version: `3.5`

### LINKED ISSUE #1618: Can not update user
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
I use ```parse-server``` as as express middleware in my ```nodejs``` application along with my own routes. I set up ```javascriptKey``` and ```masterKey``` in new ParseServer() call. So in express environment there is no ```Parse.User.current()``` as recommended. I do not use ```User.become()```. 

### Steps to reproduce
I try to update user.name like this:

```javascript
        let query = new Parse.Query(Parse.User);
        query.equalTo('username', username);
        let results = await query.find({useMasterKey: true});

        if (results.length > 0) {
            user = results.pop() as Parse.User;
            user.set('name', 'New user name');
            await user.save(null, {useMasterKey: true});
            console.log('User password updated for user ' + user.id);
        }
```

There is no errors, but user.name does not updated.

### Actual Outcome
User.name does not updated.

### Expected Outcome
User.name should be updated.

### Environment
Part of my package.json
```
"dependencies": {
    "@types/node": "18.11.2",
    "@types/express": "^4.17.14",
    "express": "^4.18.2",
    "socket.io": "^4.5.3",
    "typescript": "^4.8.4",
    "ts-node": "^10.9.1",
    "ts-node-dev": "^2.0.0",
    "vue-advanced-chat": "2.0.3",
    "uuid": "^9.0.0",
    "@types/uuid": "^8.3.4",
    "axios": "1.2.0-alpha.1",
    "jsonwebtoken": "^8.5.1",
    "@types/jsonwebtoken": "^8.5.9",
    "dotenv": "^16.0.3",
    "jssha": "^3.3.0",
    "moment-timezone": "^0.5.38",
    "moment": "^2.29.4",
    "rsdi": "2.2.2",
    "parse-server": "5.3.3",
    "parse": "^3.5.0",
    "@types/parse": "3.0.1",
    "parse-dashboard": "5.0.0",
    "multer": "1.4.5-lts.1",
    "@types/multer": "1.4.7",
    "cookie-parser": "^1.4.6",
    "@types/cookie-parser": "^1.4.3",
    "parse-dbtool": "1.0.5"
  },
```

Server
- Parse Server version: `5.3.3`
- Operating system: `Ubuntu 20.04.2 LTS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local Parallels VM at the same host`

Database
- System (MongoDB or Postgres): `Postgres`
- Database version: `15.1`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `docker image postgres:15.1-bullseye`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Javascript`
- SDK version: `3.5.0`

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

This took me quiet some time to unpack. There have been some bugs reported relating to basic functionality, such as #1596,  #1593, #1592, and [this community forum issue](https://community.parseplatform.org/t/issue-with-cdn-3-5-0/3027).

After replicating myself, [I narrowed it down](https://github.com/parse-community/Parse-SDK-JS/issues/1592#issuecomment-1305183659) to #1553. The compiled code babel is generating before and after that PR were completely different, with one using `this` in places where it would be `undefined` (in strict mode). After painstakingly trying to figure out which sub-dependancy update caused the bug, I gave up and updated all dependancies using `ncu`. Thankfully the bug was fixed, so next I went through each single change to try isolate which was necessary.

Related issues: #1599, #1596, #1593, #1592, #1601
Closes #1599
Closes #1596
Closes #1593 
Closes #1592
Closes #1601
Closes #1614
Closes #1618

### Approach

This PR adds `puppeteer` and launches a mock browser to test basic SDK functionality. In the first commit, you can see the [tests failing](https://github.com/parse-community/Parse-SDK-JS/actions/runs/3410005664/jobs/5672446555) due to the babel bug. After the dependancy update, you can see those tests pass as the problematic dependancy is updated. I have also updated some babel syntax (I was going through the entire configuration to try work out if something was depreciated).

### TODOs before merging

- [x] Add tests
- [x] Add entry to changelog

### CODE REVIEW

**Comment by dblythy** [comment]
Shoutout to @aarondill for their efforts too!

**Comment by dblythy** [comment]
Tests passing (woo!). I have added very minimal tests to the [browser dist tester](https://github.com/parse-community/Parse-SDK-JS/pull/1600/files#diff-472a58538570a6c1bc442ef2e1c855dda53130c7c9565ea5d4f7eacba4abe75a) for now - can add more if you would like

**Comment by mtrezza** [comment]
Amazing work! 🙌

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.5.1-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.1-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.5.1-beta.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.1-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.5.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.1)

**Pull request merged**
