### PR TITLE
Parse.Query.fromJSON() method

### PR DESCRIPTION
**Pull request by kyptov**
I have a lot of records in my class and I wanted to fetch some of them on the server side and continue to fetching on client side. Like an infinite scroll. So I need to query records both from server and client sides. So I wanted to send query conditions from server side to client to avoid duplication. 

Parse.Query has method toJSON, I created method fromJSON.

### CODE REVIEW

**Comment by andrejkosyak** [comment]
please pull this one

**Comment by codebreach** [comment]
Can we pull this? I can add a test cases if thats what is blocking?

**Comment by flovilmart** [comment]
@kyptov thanks for the PR (and sorry for the late response). Do you mind adding tests to cover that feature?

**Comment by kyptov** [comment]
created new one https://github.com/parse-community/Parse-SDK-JS/pull/448

**Pull request closed without merging**
