### PR TITLE
Flovilmart/readme updates

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by dplewis** [comment]
My English is really bad, plus I have my own method of testing this repo when I do PR’s. I’m curious on how you do it. Also it’s very outdated (Contribution.MD)

**Comment by flovilmart** [comment]
> plus I have my own method of testing this repo when I do PR’

How do you do it?

**Comment by dplewis** [comment]
@montymxb parse-server-test script + multiple terminal windows on my Mac + there’s no fit for mocha so I have to comment out a lot of the test

**Comment by flovilmart** [comment]
Oh wow! That’s not an optimized workflow at all :) do you use VSCODE?

**Comment by dplewis** [comment]
Nope, I’ve seen developers use it over time but never picked it up. I’ve never once set a breakpoint using parse since I started contributing

**Comment by flovilmart** [comment]
Haha :$ try the new contributing guide on parse-server then and tell me what’s broken :)

**Comment by dplewis** [comment]
I got you, but updated it here also please 🙏

Bring it to 2018

**Comment by flovilmart** [comment]
Hahaha i’ll Try :)

**Comment by flovilmart** [comment]
@dplewis for the sake of consistency, I may update the tests from mocha to jasmine for the integration.

**Comment by dplewis** [comment]
Speaking of outdated I know we want to deprecate this 

https://github.com/parse-community/parse-server-example

When I get a new client I refer to this but it’s still using Node 4.3 instead of 8. (I should be using CLI I know) Can I have access to it?

**Comment by dplewis** [comment]
@flovilmart `npm run test` + `console.log` is all I know

**Comment by dplewis** [comment]
@flovilmart Thanks a lot, I was surprise there was no issues tab, we could catch regression if it was enabled.

**Pull request merged**
