### PR TITLE
feat: Add `ParseQuery.watch` to trigger LiveQuery only on update of specific fields

### LINKED ISSUE #1806: Support LiveQuery `watch`
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

Parse Server 6 introduced `LiveQuery.watch`, a feature to only fire livequery when specified fields changed. This hasn't been introduced by this SDK yet.

### Feature / Enhancement Description

-

### Example Use Case

-

### Alternatives / Workarounds

-

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

LiveQuery watch was introducted in Parse Server 6 https://github.com/parse-community/parse-server/pull/8028

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1806

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0-alpha.3](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.2.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.2.0)

**Pull request merged**
