### PR TITLE
test: Change tests to use native MongoDB aggregation pipeline syntax

### LINKED ISSUE #1637: Prepare for Parse Server 6
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

The SDK needs to be prepared for the breaking changes coming with Parse Server 6.
As we can see in https://github.com/parse-community/Parse-SDK-JS/pull/1636, the tests are failing.

A PR to fix this may break compatibility with Parse Server <6; a compatibility table needs to be added to the README for Parse Server.

### Feature / Enhancement Description
n/a

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

CI is failing on latest Parse Server as the aggregate syntax has changed

Closes: #1637

### Approach

Changes syntax

### TODOs before merging

- [x] Add tests

### CODE REVIEW

**Comment by dblythy** [comment]
Not sure when `npm ci` is failing on node 14 - @mtrezza do you have any ideas

**Comment by mtrezza** [comment]
Maybe this is because of https://github.com/parse-community/parse-server/pull/8381 and we may have to add the same git protocol fix to the CI workflow here?

**Comment by dblythy** [comment]
Tests a bit flaky

**Comment by mtrezza** [comment]
The issue seems to be solved with the recent commit; rerunning the CI.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.6](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.6)

**Pull request merged**
