### PR TITLE
Parse.Query.fromJSON method

### PR DESCRIPTION
**Pull request by kyptov**
Made mistake with previous PR. This is new one.
Method restores query from json gained from Parse.Query.toJSON()

### CODE REVIEW

**Comment by kyptov** [comment]
@flovilmart no problem, do you mean this?
* rename `fromJSON` -> `withJSON`,
* add new static method `fromJSON` which creates new Parse.Query and calling `withJSON` method
* some test to cover this

**Comment by flovilmart** [comment]
@kyptov, yes that’s what I had in mind. Does that makes sense for you?

**Comment by kyptov** [comment]
@flovilmart made some changes

**Comment by flovilmart** [comment]
@kyptov looking great! Thanks!

**Pull request merged**
