### PR TITLE
Subscribe to object updates (LiveObject)

### PR DESCRIPTION
**Pull request by dplewis**
Closes: https://github.com/parse-community/Parse-SDK-JS/issues/594

Any advice would be appreciated.

### CODE REVIEW

**Comment by dplewis** [comment]
@flovilmart @acinader I found an existing bug in parse regarding increment. It's not a big deal but I thought it should be reported.

```
const object = new TestObject();
object.set('number', 5);
object.increment('number', 10);
object.get('number'); // returns 15
object.get('number'); // returns 25
object.get('number'); // returns 35
await object.save();
object.get('number'); // returns 15
```

https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ObjectStateMutations.js#L136

Since we don't keep track of which pendingOps we use when estimating values, increment will always compound.

**Comment by flovilmart** [comment]
How do you pass a custom liveQuery client ? I agree it’s a nice sugar, but how does it behaves in case the client disconnects? Is not connected etc...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dplewis** [comment]
I was focused on the local object changes for this PR, I didn't consider if a live query client existed. 

I believe I could reuse the current LiveQuery implementation. I'll play around with it

**Comment by flovilmart** [comment]
Ah that’s confusing, really... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by flovilmart** [comment]
Also the original requester of the feature is unlikely to use this 7 month after the initial request. I understand the motivation, but it seems that it’s the wrong solution 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dplewis** [comment]
I can post a better solution that uses LiveQueryClient that works if an object has an `objectId` if there is enough interest in this. What do you think?

**Comment by flovilmart** [comment]
I am not sure this feature makes sense at all in this kind of stateful SDK. If anything, an implementation of the SDK based on react hooks would be more valuable than any other event driven implementation. If you need this feature as it is, go ahead. I don’t want to prevent anyone from using the project as their own

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
