### PR TITLE
fix: `Parse.Query.subscribe()` does not return a rejected promise on error in Cloud Code Triggers `beforeConnect` or `beforeSubscribe`

### LINKED ISSUE #1489: Parse Cloud `beforeConnect` and `beforeSubscribe` errors should throw in `ParseQuery.subscribe`
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

To listen to a Parse Cloud beforeSubscribe error, you have to create an error.on listener. The error for beforeConnect and beforeSubscribe should trigger on `query.subscribe`

https://github.com/parse-community/parse-server/blob/443a5099059538d379fe491793a5871fcbb4f377/spec/ParseLiveQuery.spec.js#L594

### Feature / Enhancement Description

Throw on `await query.subscribe()`

### Example Use Case

-

### Alternatives / Workarounds

Leave as is

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

Cloud errors thrown from `beforeConnect` and `beforeSubscribe` will now catch, just like errors from `query.find`

Related issue: #1489
Closes https://github.com/parse-community/Parse-SDK-JS/issues/1489

### Approach

Throws error to subscription promise if error occurs

### TODOs before merging

- [x] Add tests

### CODE REVIEW

**Comment by mtrezza** [comment]
Since this is a breaking change, how would you like to proceed - add a temporary Parse Server option (or maybe there is an alternative?) or wait to merge until Parse Server 6?

**Comment by dblythy** [comment]
Which approach do you think is best? It’s not a major issue so perhaps we can wait

**Comment by mtrezza** [comment]
Can you think of a way to support both for a while without making it a breaking change or adding a Parse Server option? Otherwise up to you, whatever you think is best.

Should we add this as a feature or fix? The issue is currently classified as feature.

**Comment by dplewis** [comment]
@dblythy @mtrezza Can we get this into the 4.0.0 release?

**Comment by mtrezza** [comment]
That would be good

**Review by mtrezza — APPROVED** [review]
Looks good!

**Review by mtrezza — COMMENTED** [review]
How can be best explain the "breaking" aspect of this change?

> Calling `Parse.Query.subscribe()` will now return a rejected promise if an error is thrown in Cloud Code Triggers `beforeConnect` or `beforeSubscribe`; in previous releases a resolved promise was returned, even if subscribing failed and it was necessary to create an `error.on` listener to handle these errors.

Does that make sense?

**Comment by dblythy** [comment]
Yes, that sounds good to me

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0)

**Pull request merged**
