### PR TITLE
docs: wrong description for `Parse.User.requestEmailVerification` method

### PR DESCRIPTION
**Pull request by okobsamoht**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).

### Description
In the api reference documentation the `Parse.User.requestEmailVerification` and the `Parse.User.requestPasswordReset` have the exact same descrition for the `email parameter`.

- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.4.3-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.3-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.4.3-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.3-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.4.3](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.3)

**Pull request merged**
