### PR TITLE
Add ParseFile failing test

### PR DESCRIPTION
**Pull request by JeromeDeLeon**
#1130
@dplewis

### CODE REVIEW

**Comment by dplewis** [comment]
Which storage are you using?

**Comment by JeromeDeLeon** [comment]
Seems strange... :thinking: 

I'm using the default file storage of MongoDB

**Comment by dplewis** [comment]
Metadata and tags aren’t supported in mongo yet. I’ll open a PR for it.

You did mention an error you were receiving.

**Comment by JeromeDeLeon** [comment]
Thanks @dplewis

**Pull request closed without merging**
