### PR TITLE
refactor: Upgrade puppeteer to 23.5.0

### LINKED ISSUE #2247: Upgrade to puppeteer 22
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue

Merge https://github.com/parse-community/Parse-SDK-JS/pull/2244

### PR DESCRIPTION
**Pull request by abdullateef97**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue
 [Issue](https://github.com/parse-community/Parse-SDK-JS/issues/2247)

Closes:  [2247](https://github.com/parse-community/Parse-SDK-JS/issues/2247)

## Approach
Upgrades the puppeteer version, this has been tested with node versions `18.20.4`, `20.15.1` and `22.4.1`

### CODE REVIEW

**Comment by mtrezza** [comment]
There is some test refactor needed.

**Comment by abdullateef97** [comment]
@mtrezza please take a look again

**Comment by mtrezza** [comment]
Waiting for CI...

**Comment by mtrezza** [comment]
I've reverted the package-lock file to v2. So we can do the lock-file upgrade to v3 in a separate PR at some point.

**Comment by abdullateef97** [comment]
> I've reverted the package-lock file to v2. So we can do the lock-file upgrade to v3 in a separate PR at some point.

ok cool, looks like the CI changes have passed

**Comment by mtrezza** [comment]
Thanks for the PR!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.5](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.3.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/6.0.0)

**Pull request merged**
