### PR TITLE
fix EventEmitter undefined on React Native 0.64

### LINKED ISSUE #1335: `TypeError: undefined is not an object` with React Native v0.64 (EventEmitter)
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

#### Versions 
- React Native: 0.64
- Parse: 3.1.0

I get a error from metro bundler when I run iOS as below

```js
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[0], "../../../react-native/Libraries/vendor/emitter/EventEmitter").prototype.addListener')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

I think the error is related to 
`node_modules/parse/lib/react-native/EventEmitter.js`

```js
var EventEmitter = require('../../../react-native/Libraries/vendor/emitter/EventEmitter');

EventEmitter.prototype.on = EventEmitter.prototype.addListener;
module.exports = EventEmitter;
```

### Steps to reproduce

Build iOS with react native 0.64

### Actual Outcome

.

### Expected Outcome

Run without error

###  Environment

Client
- Parse JS SDK version: `3.1.0`

### Logs

```sh
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[0], "../../../react-native/Libraries/vendor/emitter/EventEmitter").prototype.addListener')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

### PR DESCRIPTION
**Pull request by bduyng**
fixes #1335

### CODE REVIEW

**Comment by davimacedo** [comment]
Thanks for the PR. Could you please check the failing tests?

**Comment by bduyng** [comment]
@davimacedo seems like React Native tests for passed but I got these errors. Can you help me with this?
```
1) Parse EventuallyQueue can saveEventually
  - Error: Timeout - Async function did not complete within 20000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)

2) Parse EventuallyQueue can queue destroy then save
  - Error: XMLHttpRequest failed: "Unable to connect to the Parse API"
  - MongoError: server is closed
 ```

**Comment by davimacedo** [comment]
> @davimacedo seems like React Native tests are passed but I got these errors. Can you help me with this?
> 
> ```
> 1) Parse EventuallyQueue can saveEventually
>   - Error: Timeout - Async function did not complete within 20000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
> 
> 2) Parse EventuallyQueue can queue destroy then save
>   - Error: XMLHttpRequest failed: "Unable to connect to the Parse API"
>   - MongoError: server is closed
> ```

It looks the tests were flaky but they are passing now.

**Review by davimacedo — APPROVED** [review]
LGTM!

**Comment by dplewis** [comment]
@JeffGuKang Can you see if this work? Also does this work with versions < 0.64

**Pull request merged**
