### PR TITLE
docs: remove alpha branch chapter from README

### PR DESCRIPTION
**Pull request by franklanganke**
## New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues/1422).

### Issue Description
Update default branch name 

Related issue: #1422

### Approach
- update readme.md

### TODOs before merging
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by mtrezza** [comment]
Thanks for pointing this out! I am not sure whether we want to keep that paragraph at all. We now have 2 branches (alpha, release) + in the future maybe beta + N LTS branches (release-N.x.x). To explain only the alpha branch seems a bit arbitrary. We actually have a better [branch explanation](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/CHANGELOG.md) in the changelog already, which is likely more prominent than that last paragraph in the README.

To avoid keeping redundant info that has to maintained separately, I suggest we just remove the whole paragraph (and the TOC entry).

**Review by mtrezza — APPROVED** [review]

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.4.0-alpha.3](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.4.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.1)

**Pull request merged**
