### PR TITLE
feat: Add Cloud Code context accessibility to `ParseUser.logIn`

### LINKED ISSUE #1991: Add context container in `Parse.Cloud.beforeLogin` and `Parse.Cloud.afterLogin`
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation
It is currently not possible to access context data in Parse.Cloud.beforeLogin and Parse.Cloud.afterLogin hook triggers.

### Feature / Enhancement Description
Similar to Parse.Cloud.beforeSave and Parse.Cloud.afterSave triggers, where it is possible to get context data feom the context object via the request parameter of the trigger callback.

### Example Use Case
1. This could help facilitate MFA authentication such as in cases when an email verification needs to be passed alongside parse email auth data before login is permitted.
2. It may also come in handy in context switching during or after login such as in case of performing certain actions based on context data after login.

### Alternatives / Workarounds
In my project, I was forced to use Redis cache and making additional request to the server which wasn't really necessary. 
Also, lack of this feature resulted in extra code.

### 3rd Party References
None

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1991

## Tasks

- [x] Add tests

### CODE REVIEW

**Comment by mtrezza** [comment]
I assume this needs to be merged before https://github.com/parse-community/parse-server/pull/8724?

**Comment by dplewis** [comment]
Doesn’t have to be but could help with the test cases

**Comment by mtrezza** [comment]
OK, can we merge this already, or do you want to test this out further, since this is related to another PR.

**Comment by dplewis** [comment]
You can merge it

**Comment by mtrezza** [comment]
Is this a bug fix, or rather a feature, i.e. expanding the context's accessibility? Because context is not available from everywhere, but that doesn't make it a bug. The plan is to gradually expand its accessibility.

**Comment by dplewis** [comment]
Its a feature

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.8](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.2.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0)

**Pull request merged**
