### PR TITLE
fix: initialization fails in non-browser environment that doesn't support `indexedDB`

### LINKED ISSUE #1552: Unhandled promise rejection: ReferenceError: Can't find variable: indexedDB
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
In React Native projet, I got this error when initializing parse.

### Steps to reproduce
```javascipt

import AsyncStorage from '@react-native-async-storage/async-storage';
import Parse from 'parse/react-native';

Parse.setAsyncStorage(AsyncStorage);
Parse.initialize('my-app);
Parse.serverURL = 'http://localhost:8085/parse';
```

### Actual Outcome
Unhandled promise rejection: ReferenceError: Can't find variable: indexedDB

### Expected Outcome
No errors and warnings

###  Environment

Server
- Parse Server version: `5.2.4`
- Operating system: `Windows 10`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local `

Database
- System (MongoDB or Postgres): `MongoDB `
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local `

Client
- Parse JS SDK version: `3.4.4`

### Logs
`
[Unhandled promise rejection: ReferenceError: Can't find variable: indexedDB]
at node_modules\idb-keyval\dist\compat.cjs:35:27 in safariFix__default._default.then$argument_0
at node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0        
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:248:12 in _allocateCallback$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:112:14 in _callTimer   
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:162:14 in _callReactNativeMicrotasksPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:413:41 in callReactNativeMicrotasks
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:391:6 in __callReactNativeMicrotasks
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:133:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:368:10 in __guardat node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:132:4 in flushedQueue
`

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

IndexedDB is only available in the browser. `createStore` is a promise that runs in the background. If indexedDB isn't supported, the promise rejects with `Unhandled promise rejection`.

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1552, https://github.com/parse-community/Parse-SDK-JS/issues/1440, https://github.com/parse-community/Parse-SDK-JS/issues/1505, https://github.com/parse-community/Parse-SDK-JS/issues/1441

### Approach

* Add indexedDBStorageController for `process.env.PARSE_BUILD === 'browser'`
* Check if indexedDB exists

### TODOs before merging

- [x] Add tests

### CODE REVIEW

**Comment by mtrezza** [comment]
@dplewis thanks for the PR; please request review from `@parse-community/js-sdk-review` instead of individual members, check the boxes at the top and remove TODOs that don’t apply in the template

**Review by dblythy — APPROVED** [review]

**Review by mtrezza — APPROVED** [review]

**Comment by mtrezza** [comment]
Is the PR title accurate?

**Comment by dplewis** [comment]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.5.0-alpha.6](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.5.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.5.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.0)

**Pull request merged**
