### PR TITLE
Add methods `addAll`, `addAllUnique` and `removeAll`

### PR DESCRIPTION
**Pull request by arniu**

### CODE REVIEW

**Comment by flovilmart** [comment]
Thanks for the feature, can you please not alter existing tests and instead write new tests for that feature?

**Comment by flovilmart** [comment]
@arniu on the implementation side, those all all the same as add, addUnique, remove etc... Why not just change the accepted type to `mixed | Array<mixed>` as it is the same underlying implementation.

**Comment by arniu** [comment]
@flovilmart This is mainly due to compatibility considerations:

1. Keep the API consistent with other SDK's;
2. Keep backward compatible.

In the old version, you can use `add` to add tuples to the array. For example, 

```javascript
var obj = new Parse.Object('TestObject')
obj.add('array', [1, 2])
obj.add('array', [1, 2])
```

The result is `[[1, 2], [1, 2]]`.

If you allow `add` batch to add objects, the result will be `[1, 2, 1, 2]`.

**Comment by flovilmart** [comment]
My bad, I misread the code, as it looked very similar :)

**Pull request merged**
