### PR TITLE
Add modifiers to startsWith / endsWith

### PR DESCRIPTION
**Pull request by dplewis**
Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1304

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Nice!

**Comment by mtrezza** [comment]
I'm a bit surprised we have a separate `startsWith` end `endsWith`. I would deprecate these methods to keep the codebase small, because they just seem to add a single regex char to `matches`.

**Comment by dplewis** [comment]
Yeah but nobody likes regex expressions and new users can just use the functions. They are also used in the dashboard as well.

**Comment by mtrezza** [comment]
> Yeah but nobody likes regex expressions

@TomWFox when are we launching a Parse Platform merch shop and begin printing these things on t-shirts?

**Comment by TomWFox** [comment]
http://teemill.com

**Pull request merged**
