### PR TITLE
feat: add options to enable polling and set the polling interval; fixes excessive polling

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

Related issue: https://github.com/parse-community/Parse-SDK-JS/issues/1378

Many Parse Server hosting providers charge based on API calls so the constant polling increases the API calls count per client to the point where it becomes cost-prohibitive to use.

### Approach

* Move polling to `Parse.enableLocalDatastore`
* Allow for enabling polling
* Allow for setting polling interval
* Ensure `Parse.initialize` is called before `Parse.enableLocalDatastore`
* Add documentation

### TODOs before merging

- [ ] Add tests
- [ ] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by dplewis** [comment]
Its after there must have been a typo before. All the example show that you call `enableLocalDatastore` after

**Comment by mtrezza** [comment]
ok, and what is the bug it fixes?

**Comment by dplewis** [comment]
I can break this up into 2 PRs if it helps. In this PR there is a fix for side effect from a previous feature and the PR also adds an improvement to the same feature.

**Comment by mtrezza** [comment]
Ideally it would be 2 PRs, but I guess we can leave this in 1 PR if it relates to the same feature. It adds a feature so I have to merge it as `feat` to make it a minor increment according to semver. Can you explain what bug it fixes in addition to that, so I can add that to the commit message?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.4.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.4.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.0)

**Pull request merged**
