### PR TITLE
feat: Add Bytes type to `Parse.Schema`

### LINKED ISSUE #1503: Add Bytes type to Parse.Schema
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
Is not possible to add a field using Bytes filetype.
VS Code throws an error on the 'Bytes' parameter
`Argument of type '"Bytes"' is not assignable to parameter of type 'TYPE | undefined'.ts(2345)`

### Steps to reproduce
```typescript
  const schema = new Parse.Schema('Contact')
  schema.addField('bytesField', 'Bytes')
  schema.update().then((result) => {
    console.log(result)
  })
```

I guess we need something like [Parse-Swift](https://github.com/parse-community/Parse-Swift/pull/190) feature.

### Actual Outcome
On console.log `Uncaught (in promise) Error: Bytes is not a valid type.`

### Expected Outcome
Not get the error and return the object

###  Environment
Local environment, using parse-server from the npm

Server
- Parse Server version: `latest`
- Operating system: `macOS Monterrey`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `Postgres`
- Database version: `14`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- Parse JS SDK version: `latest`

### Logs
https://community.parseplatform.org/t/saving-byte-data-to-parseobject/1804/4
https://github.com/parse-community/Parse-Swift/pull/190
https://github.com/parse-community/Parse-SDK-JS/blob/ffc523f9cd0fa2dd3fcc9754d5f15c3c1c78314f/integration/test/ParseObjectTest.js#L1365-L1379

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Uncaught (in promise) Error: Bytes is not a valid type.

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1503

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good! Is this ready for merge?

**Comment by dplewis** [comment]
Yes it’s ready

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.6](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.2.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0)

**Pull request merged**
