### PR TITLE
change issue templates according to change in parse server

### PR DESCRIPTION
**Pull request by mtrezza**
issue templates changed according to recent changes in parse server:
- https://github.com/parse-community/parse-server/pull/6805
- https://github.com/parse-community/parse-server/pull/6816
- https://github.com/parse-community/parse-server/pull/6839

changed specifically here:
- removed the "add test case", because from recent issues it was apparent that most authors do not (know how to?) create tests cases; we also don't have this in the parse server issue template.

### CODE REVIEW

**Comment by mtrezza** [comment]
@TomWFox How did you add the "Report a vulnerability" item in the issue list in parse server? I couldn't see anything in the `.github` folder regarding this.

**Comment by TomWFox** [comment]
Report a vulnerability is there by default if you have a SECURITY.MD file

**Comment by TomWFox** [comment]
Although not sure about adding a SECURITY.md file, it does pull in the one from the .github repo (and add the link in the issue type chooser). From an admin perspective it's easier to keep repos pointed to the central one - I made like 20+ PRs to change the email address in the code of conduct doc.

**Comment by mtrezza** [comment]
I'll wait for @dplewis as a frequent wanderer of the JS SDK issue list to get his approval.

**Comment by mtrezza** [comment]
> Although not sure about adding a SECURITY.md file.

Absolutely, my bad, we talk about deduplication in the docs and here I duplicate 🤦‍♂️ I'll point to the existing file and remove this one.

**Comment by TomWFox** [comment]
Github magic will do that for you - if you look at the current issue list report a vulnerability is already an option - I think the only prerequisite is to have more than one issue template (so that the issue list shows up when you click new issue)

**Comment by mtrezza** [comment]
Alright, removed the securities file, I think this is ready for review.

**Pull request merged**
