### PR TITLE
docs: Generate API documentation for release branch

### LINKED ISSUE #2034: API Reference Documentation not updated
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

The API reference doesn't redirect to the latest version of parse. There should also be a redirect to the `release` branch. Since master branch no longer exists the scripts needs to be updated.

The docs publish [job](https://github.com/parse-community/Parse-SDK-JS/actions/runs/6203726169/job/16844932081) was manually cancelled.

### Steps to reproduce

https://parseplatform.org/Parse-SDK-JS/api/

### Actual Outcome

Redirects to 4.0.1

### Expected Outcome

Redirects to 4.2.0

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Currently there is no permanent link to the documentation for the latest api. There is release version specific links but those can get stale as new releases are publish. This can be mitigated if https://github.com/parse-community/minami/pull/1 is released

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/2034

## Approach

Adds support for links that match the latest release.

Example: https://parseplatform.org/Parse-SDK-JS/api/release/Parse.html#.initialize

## Task

Waiting for https://github.com/parse-community/minami/pull/3 to be merged and released to test.

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good; is this ready for merge?

**Comment by dplewis** [comment]
This is ready for merge

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.1-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.1-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.1-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.1-alpha.1)

**Pull request merged**
