### PR TITLE
ci: Add concurrency to cancel previous workflow runs

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

Adds concurrency to minimise the amount of outdated workflows that are run.

Closes: n/a

### Approach

n/a

### TODOs before merging

n/a

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Thanks for this!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.4](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0)

**Pull request merged**
