### PR TITLE
fix: `Parse.File.cancel` starts new attempt to save file

### LINKED ISSUE #1162: Unsuccessful cancellation of Parse File
### Issue Description

I was trying to cancel an a PFile when I noticed in my network that it successfully cancelled the PFile but created another request to continue saving the file. I tried checking who called it the second time and to my surprise, it went another attempt to save the file because of [this](https://github.com/parse-community/Parse-SDK-JS/blob/0923c93aecd2ad46f4c0d03e8a838e5fa8eeafa2/src/RESTController.js#L129).

### Steps to reproduce

1. Create a ParseFile using JS SDK
2. Save it
3. Create a setTimeout to mimic interruption after 2s
4. Cancel it

### Expected Results

Cancel the file

### Actual Outcome

Cancel the first request, then shortly after created another request to continue the previous one.

### Test Case

I don't know how will I be able to reproduce this one on a test

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.2.0
  - Operating System:     Ubuntu 18.04
  - Hardware:             
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **JS SDK**
  - JS SDK version: 2.13.0
  - Application? (Browser, Node, React-Native, etc): Browser

### Logs/Trace

image

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1162

## Approach

* Properly handle `npm run watch:browser` compiling to the `/dist` directory
* Add missing `_aborted` check

## Viewing the Network Requests with puppeteer
Disabling headless mode to launch chromium
Showing devtools on load
`userDataDir` is used to store `preserve logs` peference in the network tab
```
browser = await puppeteer.launch({ args: ['--disable-web-security'], headless:false, devtools: true, userDataDir: path.resolve(__dirname, './myUserDataDir') });
```

To keep chromium running use setTimeout, `done`, Jasmine timeout. If network requests aren't showing set 5 second timeout around `page.evaluate`

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by mtrezza** [comment]
Seems there are still commits being made, so removing the review request

**Comment by dplewis** [comment]
@mtrezza The reason for the commits is because this PR introduces a flaky test and I don't know why. Can you re-run the CI?

**Comment by mtrezza** [comment]
Sure, rerunning...

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.2.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.2.0)

**Pull request merged**
