### PR TITLE
fix: Live Query not working on Expo React Native

### LINKED ISSUE #2082: Expo RN and ParseLiveQuery EventEmitter error
### New Issue Checklist

- [ X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ X] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [ X] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
I updated a lot of dependencies in the last weeks and now I cannot get my application into a working state.
The problem seems to be related to the React Native Parse Live Queries but I did not find anything that could help me to debug this in a good way. I did not change anything in the config regarding Parse however I think it is due to the latest updates.

### Actual Outcome

Screenshot 2024-02-04 at 15 50 55

###  Environment

Server
- Parse Server version: 6.2.0

Client
- Parse client version: 4.3.1
- React Native 0.73.2
- Expo 50

This is how my config is setup:
```
import Parse from "parse/react-native.js";
import AsyncStorage from "@react-native-async-storage/async-storage";

// Initialize Parse Backend Back4app
const parseConfig = {
  applicationId: "...",
  javascriptKey: "...",
  serverURL: "...",
  liveQueryServerURL: "...",
};

//Before using the SDK...
Parse.setAsyncStorage(AsyncStorage);
Parse.initialize(parseConfig.applicationId, parseConfig.javascriptKey);
Parse.serverURL = parseConfig.serverURL;
Parse.liveQueryServerURL = parseConfig.liveQueryServerURL;

// Enable cached user
Parse.User.enableUnsafeCurrentUser();

export default Parse;
```

And I do subscribe to the queries by:
```
parseQuerySub = await parseQuery.subscribe();

parseQuerySub.on("create", (myStuff: MyStuff) => {
    do stuff
}

```

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

https://github.com/parse-community/Parse-SDK-JS/pull/1999 introduced swappable custom EventEmitters for runtimes that didn't include Node's builtin EventEmitter or React-Native. 

Fixed
```
start.js:39 Uncaught (in promise) TypeError: Class extends value undefined is not a constructor or null
    at node_modules/parse/lib/node/LiveQuerySubscription.js (LiveQuerySubscription.js:100:42)
```
The LiveQuery modules no longer extends from the EventEmitter (would break if EM doesn't exist) but copies `on` and `emit` from the prototype chain in the constructor where EM could exist. [RN: Use a Private Property in EventEmitter](https://github.com/facebook/react-native/pull/39395) created a private property in the `addListener` (copied to `on`). This breaks RN since we are trying to access a private property from a non-instance class (no longer extends so not an instance of EventEmitter therefore no access)

`TypeError: attempted to use private field on non-instance`

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/2082, https://github.com/parse-community/Parse-SDK-JS/issues/2081, https://github.com/parse-community/Parse-SDK-JS/issues/1766, https://github.com/parse-community/Parse-SDK-JS/issues/1522

## Approach

Instead of inheriting from the EventEmitter just use a wrapper.

This has been tested on 

```
  "dependencies": {
    "@expo/metro-runtime": "3.1.3",
    "@react-native-async-storage/async-storage": "1.21.0",
    "expo": "50.0.15",
    "expo-status-bar": "1.11.1",
    "parse": "5.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.6",
    "react-native-get-random-values": "1.11.0",
    "react-native-web": "0.19.6"
  },
```

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by dplewis** [comment]
@mtrezza This has been tested by @martinpfannemueller  https://github.com/parse-community/Parse-SDK-JS/issues/2081#issuecomment-2053953406

**Review by mtrezza — APPROVED** [review]

**Review by mtrezza — COMMENTED** [review]
So this PR can be closed without merging?

**Comment by dplewis** [comment]
> So this PR can be closed without merging?

This can be merged. This PR fixes the issue posted and has been tested by multiple developers using Expo / React-Native

**Comment by mtrezza** [comment]
If it fixes an issue, could you add a test for the issue?

**Comment by dplewis** [comment]
Should I add an Expo react native starter project to the SDK and run it in the CI?

**Comment by dplewis** [comment]
@mtrezza I added a test, looks like codecov is broken again.

**Comment by mtrezza** [comment]
~~I believe what you are trying to say is that it's too much effort to write a test for it? So we'll merge without test.~~

Edit: Thanks for adding a test.

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.4](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0)

**Pull request merged**
