### PR TITLE
build: Release beta

### PR DESCRIPTION
**Pull request by mtrezza**

### CODE REVIEW

**Comment by mtrezza** [comment]
@dblythy did we forget anything here in the node 16 CI? the node 16 tests are consistently failing with connection errors. could you take a look?

**Comment by dblythy** [comment]
I will investigate

**Comment by mtrezza** [comment]
Interestingly, the Node 16 tests for the latest commit on the alpha branch seemed to pass except for one flaky test. So it's strange this is failing in this PR where the only difference is commit [5b31b9f](https://github.com/parse-community/Parse-SDK-JS/pull/1658/commits/5b31b9fb4f0fe669175f5c6f8f811ca3e904ebab). It may be something that occurs due to the merge.

**Comment by mtrezza** [comment]
Ran the Node 16 tests again and they passed except for 1 flaky test. There may be some other issue with the CI. Going ahead and merging.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.6](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.6)

**Pull request merged**
