### PR TITLE
fix: Connection failure in `Parse.Object.saveEventually` and `Parse.Object.destroyEventually` not handled on custom `Parse.Error.CONNECTION_FAILURE` message

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Use error codes instead of hard coded messages for connection failures. With the addition of custom Error messages, changing the default connection failure message would cause an error.

Related: https://github.com/parse-community/Parse-SDK-JS/pull/2014

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by mtrezza** [comment]
Could you please describe the issue in more detail? This PR has no issue linked and no issue description.

**Comment by dplewis** [comment]
Updated the OP, I don't know how that happened lol

**Comment by mtrezza** [comment]
It's difficult for me to review the PR because the description under "Issue" describes the change in this PR, not the bug. And there is no issue linked with an issue description. Also the PR title describes the fix, while it should only describe the bug.

Could you please:
- Add an issue description
- Change the PR title to describe the bug; remember that it will be part of the changelog

**Comment by mtrezza** [comment]
I've changed the PR title to the best of my ability, although I'm still not sure what the issue here is. The PR seems to identify the connection error state by the error code now instead of the error message, which seems more robust. I assume this was a problem when calling the `...eventually` methods. If you could clarify the issue in the issue description above and if necessary adapt the PR title, then we can merge.

**Comment by dplewis** [comment]
The issue is with the introduction of Custom Parse Error Messages, a custom connection failure message would break this. This was partially added https://github.com/parse-community/Parse-SDK-JS/pull/2014/files#diff-0569cde5238e6df9fc3d56e880efe2653bb1bf438be2c70dc1b504f5def263c5L278 but was missed for some reason.

**Review by mtrezza — APPROVED** [review]
Looks good; thanks for expanding the PR title

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-alpha.3](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.1-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.1-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.1-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.1-alpha.1)

**Pull request merged**
