### PR TITLE
When traversing fields, ensure we create them as we go to avoid acces…

### LINKED ISSUE #1299: How to increment a nested object field ?
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

This is a simpler case version of issue #6687. I'm not sure if i'm doing anything wrong, but i think this should work

I'm trying to increment a value of a newly created object. 

Ex:
```js
db.test.findOneAndUpdate(
    {"_id":"20mMYzLTjx"} ,
    {$inc:{ "a.b.c.d" : 1 }}
)
```

### Steps to reproduce

```js
const obj= await Parse.Object
    .extend('test')
    .createWithoutData('20mMYzLTjx').fetch()

// obj.get('a') === {}   (my schema defaults a to {}

obj.increment('a.b.c.d' , 1 )
await obj.save()

```

### Actual Outcome

```
TypeError: Cannot read property 'd' of undefined at Object.estimateAttributes (.....parse-server\node_modules\parse\lib\node\ObjectStateMutations.js:234:28)
```

Seems to me that https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ObjectStateMutations.js#L140

```patch
          for (let i = 0; i < fields.length - 1; i++) {
-            object = object[fields[i]];
+            object = object[fields[i]] || {}; 
          }
```

### Expected Outcome

Path `a.b.c.d` get created and persisted

### Failing Test Case / Pull Request

- [x] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `v4.5.0 /  3d76643286d41b954b6c8e2d6614657c891a31e7`
- Operating system: `Win 10`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local` 

Database
- System (MongoDB or Postgres): `Mongo`
- Database version: `4.4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `remote/self hosted`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Js`
- SDK version: `2.17.0`

### PR DESCRIPTION
**Pull request by sadortun**
Fix #1299

### CODE REVIEW

**Comment by davimacedo** [comment]
@sadortun thanks for the PR. Could you please add a test case?

**Comment by sadortun** [comment]
@davimacedo  Here you go ! Merry Christmas :) ! 

Please ensure you check/test for other possible side effects :) I'm new to the wonderful world of `Parse` and i would really like to avoid destroying thousands of client apps :) hehehe

**Comment by dplewis** [comment]
@sadortun Can you add an integration test in `integration/test/ParseObjectTest.js`

I wrote a test and it fails

```
fit('can increment nested on undefined field', async () => {
    const obj = new TestObject();
    obj.increment('a.b.c.d');
    await obj.save();

    console.log(obj.get('a')); // undefined

    const query = new Parse.Query(TestObject);
    const result = await query.get(obj.id);
    console.log(result.get('a')); // undefined
  });
```

**Comment by sadortun** [comment]
@dplewis thanks for the hint, I'll look at it!

**Comment by dplewis** [comment]
@sadortun The following tests pass with your fix. 

```
it('can increment nested four levels', async () => {
    const obj = new TestObject({ a: { b: { c: { d: 1 } } } });
    await obj.save();
    obj.increment('a.b.c.d');
    console.log(obj.get('a').b.c.d); // 2

    await obj.save();
    console.log(obj.get('a').b.c.d); // 2

    const query = new Parse.Query(TestObject);
    const result = await query.get(obj.id);
    console.log(result.get('a').b.c.d); // 1
  });
```

The failing test I posted is a separate issue, its failing because serverData doesn't exist when you increment. This is caused by: https://github.com/sadortun/Parse-SDK-JS/blob/patch-1/src/ParseObject.js#L744

To fix you need to remove that and do an update on the server side.

For your fix, can you add the passing test I posted and we can merge this in. We can do a separate issue for the bug I found.

**Comment by sadortun** [comment]
Thanks @dplewis ill get back to you later today or early tomorow

**Comment by sadortun** [comment]
1)
Hi @dplewis Took some time, but i'm back ! I added the test.

2)
Also FYI,  seems like `mustache` is required but not in `devDependencies`


3) 
I should also probably add/exclude your failing test from https://github.com/parse-community/Parse-SDK-JS/pull/1301#issuecomment-782180680 to ensure it's documented and get fixed :)  Let me know!

**Review by dplewis — APPROVED** [review]
LGTM! I'm going to open a PR for that other issue I pointed out.

> Also FYI, seems like mustache is required but not in devDependencies

I don't know what that is.

**Comment by sadortun** [comment]
Awesome! Any idea when this (and the other PR) will be available in a release ?

Thanks a lot you guys are awesome!

**Comment by dplewis** [comment]
Thanks we try to do a release every 2 weeks. You can use the master branch if you need it.

https://github.com/parse-community/Parse-SDK-JS#want-to-ride-the-bleeding-edge

**Pull request merged**
