### PR TITLE
ci: Fix flaky tests due to open server connection

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

Sometimes the job status is returned as `running` when it should be `failed`. The status is returned too quickly before the job failed. 

```
Parse Cloud run failing job
  Message:
    Unhandled promise rejection: AssertionError [ERR_ASSERTION]: 'running' == 'failed'
```

I've taken initial steps to find the fix for this. Once a test finishes there shouldn't be any open connections to the server. If there are then we log them in the CI and fix the as we go. Hopefully we can find which test is leaking.
```
- Error: Timeout - Async function did not complete within 20000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
        - MongoNotConnectedError: Client must be connected before running operations
```

I removed the beforeAll from `ParseDistTest` as I only recommend using only one beforeAll in the test suite (one already exists in `helper.js`). I ensured the headless browser closes and doesn't leave any connections to the server.

### Approach

Refactor Cloud Code Jobs to wait for the job status to change.

### TODOs before merging

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Review by mtrezza — COMMENTED** [review]
Glad this is fixed, can we merge?

**Comment by dplewis** [comment]
@mtrezza This can be merged

**Comment by dplewis** [comment]
@mtrezza The issue is reconfigureServer for sure or related to it as I mentioned [here](https://github.com/parse-community/Parse-SDK-JS/pull/1666#issuecomment-1405862007)

Screen Shot 2023-01-27 at 10 04 24 AM

**Comment by dplewis** [comment]
@mtrezza I also noticed that the Node 14 build takes 17 minutes because of the mongodb-runner being installed globally. Should we move it to the devDependencies to increase the speed.

Screen Shot 2023-01-27 at 10 57 32 AM

**Comment by mtrezza** [comment]
I guess we can move it; do you know what this is only affecting Node 14?

**Comment by dplewis** [comment]
I have no idea, the server tests work just fine for Node 14.

**Comment by mtrezza** [comment]
It could be this:

https://github.com/parse-community/Parse-SDK-JS/blob/bea817e92ea2e390338e3c989d26e32ada8e550f/.github/workflows/ci.yml#L37-L39

But this has been added because otherwise some dependencies won't download at all.

**Comment by mtrezza** [comment]
Is this ready for merge?

**Comment by dplewis** [comment]
@mtrezza this is ready to merge once the 17 minute CI passes. I'll play around with the CI for node 14 to see if I can find a better fix

**Comment by mtrezza** [comment]
The 17min CI passed, I'll go ahead and merge

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.7](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.7)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.1-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.1-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.1)

**Pull request merged**
