### PR TITLE
feat: `LiveQueryClient.close` returns promise when WebSocket closes

### LINKED ISSUE #1734: Ensure LiveQueryClient closes
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Feature / Enhancement Description

There are a lot of events that happens when the client closes. I want to know when the websocket itself closes. This is useful for testing and ensure that connections to the server are closed.

### Example Use Case

Allow close to return a promise
```
const client = await Parse.CoreManager.getLiveQueryController().getDefaultLiveQueryClient();
await client.close();
```

### Alternatives / Workarounds

The websocket closes in the background so you will have to set a timeout.
```
client.close();
sleep(1000);
```

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1734

## Approach

* Returns Websocket CloseEvent [@see link](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close_event)
* Improves tests to ensure server connections are closed properly.
* Improve WeChat Mini Websockets onclose event [@see link](https://developers.weixin.qq.com/miniprogram/en/dev/api/network/websocket/wx.onSocketClose.html)
* Ensure socket exists

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by mtrezza** [comment]
Is this a breaking change?
Is this a fix or a feature/improvement?

**Comment by dplewis** [comment]
This is not a breaking change, it’s an improvement

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.12](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.12)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0)

**Pull request merged**
