### PR TITLE
Update ws to 3.3.1

### PR DESCRIPTION
**Pull request by montymxb**
Updates to **3.3.1** to meet node security guidelines.

### CODE REVIEW

**Comment by montymxb** [comment]
parse-server-push-adapter depends the JS sdk. Once this is patched up it should pass validation as well.

**Comment by montymxb** [comment]
👍 . We'll also need to bump to **1.10.2** so we reference this. Want me to take care of that or do you want to do that?

**Comment by flovilmart** [comment]
Go ahead!

**Comment by montymxb** [comment]
@flovilmart Release [1.10.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/v1.10.2) is up :zap:! Still need to publish the updated npm package however, don't have access to it personally.

**Comment by flovilmart** [comment]
And it's published!@

**Pull request merged**
